### ISSUE TITLE
Resource subscription.

### ISSUE THREAD

**Issue by jairoseros** [ankraft/onem2mlib#1]
Hello.

Well this is not an issue. I would like to know how to make a subscription and it will be nice if you can explain to me how the notifications.py file works.

Best regards.

**Comment by ankraft** [comment]
Thank you for your question.
Please have a look at the example in [subscription.py](https://github.com/ankraft/onem2mlib/blob/master/examples/subscription.py). This gives you a short introduction about how to add a subscription to a resource and how the handling is done.

You also don't really need to work with the notification.py file. It does the handling for received notifications by setting up a local http server to receive the notifications from a CSE, as well as executing the callback functions for the notifications.

Basically, working with subscriptions works like this:
- Import the Notification sub-module in your application and call the setup method ``setupNotifications()`` from this sub-module. This creates and starts the http server. You can do some configurations here, but the most important thing is that you can provide a default callback function that is called every time a notification is received and there is no other callback function specified.
- You write one or more callback functions for handling the notifications. The only argument for a callback function is a resource object, ie. the resource of the notification.
- Next, you get or create a resource you like to monitor and call the ``subscribe()``method of that resource. You also can add individual callback functions (or lambdas if you like) for each resource to do easier notification handling.
- At the end of your application you should call the ``shutdownNotifications()`` function from the Notification sub-module (though this is done implicitly when your application terminates).

**Comment by jairoseros** [comment]
Thanks for your help.

Very nice module. It helps me a lot.
